# Generated by Django 4.1.7 on 2023-03-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='teams',
            new_name='team',
        ),
    ]
